baseURL = "/"
languageCode = "en-us"
title = "Smart Architectures"
theme = "hugo-book"

# Book theme settings
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = "light"
  # Logo image for the site
  # Favicon for the site
  BookFavicon = '/logo.svg'
  
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  BookToC = true
  
  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'logo.png'
  
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = "docs"
  
  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = "https://github.com/yourusername/genai-patterns"
  
  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # BookEditPath = "edit/main/content"
  
  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = "Jan 2, 2006"
  
  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch = true

[menu]
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/yourusername/genai-patterns"
    weight = 10